In [1]:
#new list + [(st of if) if (cond) else( st of else) for]
l1=[23,56,78,5,4,2,59]
res=[i*i if i>50 else 'x' for i in l1]
print(res)

['x', 3136, 6084, 'x', 'x', 'x', 3481]


In [5]:
#take the salary from the user if the sal is < 50k d0 10@ other wise 15@
#s=int(input("enter the salary"))
l4={4500,55000,30000,75000}#salarry is taken in list
l2=[ i-(i*0.1) if i==0 and i<=50000 else i-(i*15/100) for i in l4 ]
print(l2)

[46750.0, 25500.0, 3825.0, 63750.0]


In [11]:
#dictionary
dict={1:'MENTOR',5:'SHIVA',10:'venkate','konda':7}
#print(dict)
#print(dict.keys())
#print(dict.values())
print(dict[5])

SHIVA


In [12]:
dict1={"dep":"CSE","details":{"year":"2","sec":"D","count":71}}
print("year is", dict1["details"]["year"])
print("section is", dict1["details"]["sec"])
print("strenth is", dict1["details"]["count"])

year is 2
section is D
strenth is 71


In [15]:
idl =[34,56,78,90,100]
names=["joe","suji","subu","konda"]
new=(zip(idl,names))
for i in new:
  print(i)

(34, 'joe')
(56, 'suji')
(78, 'subu')
(90, 'konda')


In [18]:
# NUMPY
import numpy as np
A = np.array([1,2,3,4]) #id array
print(A.ndim)
print(A.shape)

1
(4,)


In [27]:
# 2d array
import numpy as np
B=np.array([[2,4,5,6],[4,7,8,6]]) # elements in each row = columns
print(B.ndim)
print(B.shape)
print(B)

2
(2, 4)
[[2 4 5 6]
 [4 7 8 6]]


In [35]:
# group array
import numpy as np
C=np.array([[[2,4,5],[4,7,8],[4,7,0]],[[4,6,0],[5,2,8],[0,6,8]]]) # elements in each row = columns
print(C.ndim)
print(C.shape)
print(C)

3
(2, 3, 3)
[[[2 4 5]
  [4 7 8]
  [4 7 0]]

 [[4 6 0]
  [5 2 8]
  [0 6 8]]]


In [37]:
#numpy using zero
A=np.zeros((2,4,5))
print(A)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [38]:
#numpy using eye
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [41]:
#numpy range
A=np.arange(11)
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [43]:
#print all the no. that are % dy 8 using arange function b/w 1 and 1000 numbers
A=np.arange(8,1001,8)
print(A)

[   8   16   24   32   40   48   56   64   72   80   88   96  104  112
  120  128  136  144  152  160  168  176  184  192  200  208  216  224
  232  240  248  256  264  272  280  288  296  304  312  320  328  336
  344  352  360  368  376  384  392  400  408  416  424  432  440  448
  456  464  472  480  488  496  504  512  520  528  536  544  552  560
  568  576  584  592  600  608  616  624  632  640  648  656  664  672
  680  688  696  704  712  720  728  736  744  752  760  768  776  784
  792  800  808  816  824  832  840  848  856  864  872  880  888  896
  904  912  920  928  936  944  952  960  968  976  984  992 1000]


In [45]:
# spliting arange of numbers into n numbers with common differences
A= np.linspace(3,2,12)
print(A)

[3.         2.90909091 2.81818182 2.72727273 2.63636364 2.54545455
 2.45454545 2.36363636 2.27272727 2.18181818 2.09090909 2.        ]
